In [86]:
import numpy as np

In [87]:
tmp = np.zeros([1,11*3])
tmp.shape

(1, 33)

In [88]:
a1 = [1,2,3,4]
a11 = np.array([a1[1:]])
a11.shape

(1, 3)

In [89]:
index = 0

In [90]:
if a1[0] == 1:
    tmp[:,index:index+3] = a11
    index+=3

In [91]:
tmp.shape

(1, 33)

In [92]:
a1 = [1, 45,8,6]
a11 = a2[1:]

In [93]:
if a1[0] == 1:
    tmp[:,index:index+3] = a11
    index+=3
tmp

array([[ 2.,  3.,  4., 45.,  8.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [94]:
a1 = [1, 5,4,63]
a11 = a1[1:]

if a1[0] == 1:
    tmp[:,index:index+3] = a11
    index+=3
tmp

array([[ 2.,  3.,  4., 45.,  8.,  6.,  5.,  4., 63.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [95]:
tmp

array([[ 2.,  3.,  4., 45.,  8.,  6.,  5.,  4., 63.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [96]:
tmp = tmp.reshape(1,11,3)
tmp

array([[[ 2.,  3.,  4.],
        [45.,  8.,  6.],
        [ 5.,  4., 63.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [97]:
a1 = [1, 5,4,63]
a11 = a2[1:]

if a1[0] == 0:
    #tmp = tmp.reshape(1, 11*3)
    tmp = np.zeros([1,11*3])
    index = 0
tmp

array([[[ 2.,  3.,  4.],
        [45.,  8.,  6.],
        [ 5.,  4., 63.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [98]:
a = np.argmax(tmp[:,:])
a

8